import type { Metadata } from "next";
import { Cabin, Sora } from "next/font/google";
import "./globals.css";

const cabin = Cabin({
  variable: "--font-cabin",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabin.variable} ${sora.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
